name: pilz
favicon: null
layout_spectrum: 0.54487
typography_spectrum: 0.4329024546314031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4881808618083596
  lightness: 0.5322241659741849
  saturation: 0.23327535693533719
  rhythmicContrast: 0.5286382471676916
purpose: []
